### ISSUE TITLE
Accreditation portlet renders an error for anonymous users

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#301]
## Steps to reproduce

Browse to the Front Page w/o being logged in.

## Current behavior

The accreditation portlet is rendered red which indicates an error

## Expected behavior

No Portlet is rendered if the contents are not accessible by anonymous users

## Screenshot (optional)

<img width="1423" alt="Accreditation Portlet" src="https://user-images.githubusercontent.com/713193/31989096-95177664-b971-11e7-8490-b5bb015c9db9.png">

**Comment by Nihadness** [comment]
@xispa and @ramonski , I am not sure if the PR I created solves that problem in the most proper way. I approached to that problem like _If a user not logged in, then cannot see accreditation portlet_. So, if the user doesn't have ID, do not render this portlet.
Do you think adding portlet _Renderer_ class would be a better solution? Like in this example maybe:
https://docs.plone.org/4/en/old-reference-manuals/portlets/tips.html#available-property
Since we use `portlets.xml` to define portlets, I didn't want to touch it.
