### ISSUE TITLE
Worksheet: Assign-Buttons do not appear anymore after sort-change

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#305]
## Steps to reproduce

Create a new Worksheet and click on the AR column header

## Current behavior

The "Assign" buttons do not appear anymore on checkbox-selecting an Analysis

## Expected behavior

The "Assign" button appears on Analyses selection

## Screenshot (optional)

Expected:
<img width="956" alt="ws17-0004_ _liscon_lims" src="https://user-images.githubusercontent.com/713193/31990719-2e5312ee-b976-11e7-98a9-117240a73799.png">

Current situation after the Analyses were sorted by AR ID:
<img width="910" alt="ws17-0004_ _liscon_lims" src="https://user-images.githubusercontent.com/713193/31990791-55555096-b976-11e7-8e5f-7a07e461e384.png">

**Comment by xispa** [comment]
This problem occurs in all bikalistings. When the user clicks to a sortable header, the system fires an ajaxsubmit that returns a new html table with the items sorted in accordance with the header clicked. The same ajaxsubmit (thanks to `replaceTarget` option), replaces the current table with the new one:

https://github.com/senaite/bika.lims/blob/696a1047180bbac39ecc0f0a58e145f1bb2ba2a1/bika/lims/browser/js/bika.lims.bikalisting.js#L138-L147

Because of the dynamic loading of transitions https://github.com/senaite/bika.lims/pull/150 , the list returned by the ajaxsubmit does not include the available transitions for each item, so only transitions defined in `custom_actions` are displayed. Since in Worksheet's add Analyses view there is no `custom_actions` defined, no action buttons are displayed at the bottom of the list.
