### ISSUE TITLE
Traceback on AR Attachment upload

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#323]
## Steps to reproduce

1. Create a new AR and receive the Sample
2. Upload an Attachment

## Current behavior

Traceback occurs

## Expected behavior

Attachment is added to the AR or to an Analysis

## Screenshot (optional)

Traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.attachment, line 81, in __call__
  Module bika.lims.browser.attachment, line 132, in action_add
  Module bika.lims.api, line 166, in create
  Module Products.Archetypes.BaseObject, line 636, in processForm
  Module bika.lims.content.attachment, line 126, in _renameAfterCreation
  Module bika.lims.idserver, line 215, in renameAfterCreation
  Module bika.lims.idserver, line 192, in generateUniqueId
  Module bika.lims.idserver, line 143, in next_id
IndexError: list index out of range
```

**Comment by Nihadness** [comment]
This error happens because we don't add _Attachments_ to any catalog in setup handler:https://github.com/senaite/bika.lims/blob/senaite-integration/bika/lims/setuphandlers.py#L402 .
I faced this error during last week of Integration and @rockfruit didn't want me to add Attachments to any catalog, and said he would solve it soon. I think he had something in his mind.

**Comment by rockfruit** [comment]
Thanks for the reminder, I'd forgotten that.
