### ISSUE TITLE
Cleanup deprecation warnings

### ISSUE THREAD

**Issue by xispa** [senaite/bika.lims#341]
Tracelog prints too much deprecation warnings at the moment. We should ensure the version is deprecation-warnings free asap. Doesn't make sense the core application itself is calling to deprecated functions.

Some that should be easy to address:
- Call to deprecated function 'bika.lims.content.labcontact.getDepartment'. [1612] Use getDepartments instead
- Call to deprecated function 'bika.lims.content.abstractroutineanalysis.getAnalysisRequestTitle'. [1709] Use getRequestID instead
- Call to deprecated function 'bika.lims.content.abstractroutineanalysis.getAnalysisRequestURL'. [1709] Use getRequestURL instead
- Call to deprecated function 'bika.lims.content.abstractroutineanalysis.getAnalysisRequestUID'. [1709] Use getRequestUID instead

**Dismiss deprecation warnings that are related with workflows** (events, guards), such as:
- Call to deprecated function 'bika.lims.content.sample.guard_receive_transition'. [1705] Use bika.lims.workflow.sample.guards.receive
- Call to deprecated function 'bika.lims.content.analysisrequest.workflow_script_receive'. [1705] Use events.after_receive from bika.lims.workflow.anaysisrequest
- etc.

cause they are being addressed in workflow branch https://github.com/senaite/bika.lims/tree/workflow-sampling  , that will be merged soon.

**Comment by rockfruit** [comment]
In some cases, the only way to prevent the deprecations was to remove the deprecated functions (for example, functions that were called to populate catalog indexes and metadata).

I believe that evo 1.1.x (senaite-integration) is a good opportunity to remove these deprecations, and so I've done so.

I've also removed the @deprecated decorators from the workflow functions since I know we will be merging the new workflow branch soon, and these are not functions which anyone will mistakenly use directly.  Currently the tests pass, and the only remaining deprecatin that's printed is this one:

> bika.lims/bika/lims/browser/bika_listing.py:982: DeprecationWarning: Call to deprecated function 'bika.lims.browser.bika_listing._folderitems'. Using bikalisting.folderitems(classic=True) is very slow
