### ISSUE TITLE
Setup Analysis Services Listing Table: Sortkey not working

### ISSUE THREAD

**Issue by grulisco** [senaite/bika.lims#359]
The standard sorting of analysis services is arbitrary, not sorted in any visible manner.
Analysis Services Table neither contains sortkey column, nor it is selectable via popup menu.
So sorting by sortkey in this view is corrupted.

**Comment by xispa** [comment]
As per https://github.com/senaite/bika.lims/pull/307 and https://github.com/senaite/bika.lims/pull/331 , Analysis Service with a Sort Key value defined will appear first, and sorted by Sort Key ascendant. The rest of items appear below, sorted by title ascending.

The list should be similar as this:
![as_sorted](https://user-images.githubusercontent.com/832627/32469973-8f54e0de-c355-11e7-86e2-af4321e42fb3.png)

Note that Sodium appears before Iron because the former has a SortKey=10 and the latter a Sortkey=20. After them (because they don't have any value assigned for SortKey), appear the rest of Analysis Services, but sorted alphabetically ascending.

Please, confirm if your Analysis Services list don't get sorted following this criteria by default. If not, maybe the problem is that bika_setup_catalog needs to be reindexed for the changes to take effect.

**Comment by ramonski** [comment]
Thanks @xispa, I will do a `bika_setup_catalog` clear&rebuild later this day and report back.

**Comment by ramonski** [comment]
Rebuilt `bika_setup_catalog` and it seems to be still not working (difficult to verify, because it is not possible to show the `sort_key` column in the listing #360).

I verified that the `sortable_title` index exists in `bika_setup_catalog` and also contains correct values with the prefixed the sort keys.

<img width="1423" alt="sortable_title" src="https://user-images.githubusercontent.com/713193/32482498-49dfb57c-c398-11e7-931e-98f3ee5a222c.png">

**Comment by xispa** [comment]
https://github.com/senaite/bika.lims/pull/362 fixes this issue.
