### ISSUE TITLE
Change the default installation Screen

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#376]
## Steps to reproduce

Create a new Senaite instance

## Current behavior

The default Bika installation screen is shown

## Expected behavior

The SENAITE installation screen is shown

## Screenshot (optional)

![distribution_installieren](https://user-images.githubusercontent.com/713193/32737540-a3ea0624-c89a-11e7-8512-6e5acc6eea17.jpg)

**Comment by Nihadness** [comment]
@ramonski , in order to avoid confusion, I would like to offer replacing _Check Boxes_ with **_Radio Buttons_** in _Add-on's_ list, since choosing the _most top_ add-on will install the rest. Because, when more than one 'Add-on' is chosen, then they are not installed in order, and a lower layer can be run after upper layer.
For example, if someone chooses `'Bika Health'` and `'Bika Lims' `, then system installs `'Bika Health'` first (because of alphabetical sort), then while `'Bika Lims'` is being installed, it runs `setuphandler` of  `'Bika Lims'` which removes features of `'Bika Health'`.

**Comment by ramonski** [comment]
Can be closed after https://github.com/senaite/bika.lims/pull/488 was merged
