### ISSUE TITLE
Missing Verify Button in AR Lists

### ISSUE THREAD

**Issue by grulisco** [senaite/bika.lims#449]
## Steps to reproduce
Create, receive ARs
Submit results for verfication
Go to an AR List
Mark at least one AR in state "to be verified"

## Current behavior
Many operations (Retract, Cancel, ....) appear under the AR listing but not "Verify".
IIRC one could verify this way in earlier bika lims versions...

## Expected behavior
Verify buttons appears in addition to the others

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/33661404-0bdea29a-da88-11e7-95a5-9a06d9b89f1e.png)

**Comment by xispa** [comment]
The AR should automatically transition to `verified` state once all its analyses are verified. Some time ago we had the "verify" button in AR list, but was removed because it was so easy for labman users to verify directly ARs without even looking at results. Please confirm if the AR is automatically transitioned to `verified` state after verifying its analyses, also if some were retracted.

**Comment by grulisco** [comment]
Well, that's a good argument, that I fully agree with. I just wondered whether it was kind of a failure in this current merging process.
There are no problems so far with the verified state if analyses were verified via single AR or via worksheets.
With senaite/bika.lims#350 we might have a comfortable way to step between ARs...

**Comment by xispa** [comment]
Cool, thanks!
